export const pricing = [
  {
    title: "Landing Page",
    description: "Para lanzamientos y campañas",
    bestSeller: false,
    price: 280,
    priceArs: 390000,
    // salePrice: null,
    features: [
      "Dominio .com.ar incluido",
      "Hosting incluido",
      "Diseño responsive",
      "Optimización SEO",
      "Email info@tumarca.com",
      "1 página",
      "Entrega en 1-2 semanas",
    ],
  },
  {
    title: "Web Corporativa",
    bestSeller: true,
    price: 470,
    priceArs: 590000,
    // salePrice: null,
    description: "Para empresas y profesionales",
    features: [
      "Dominio .com.ar incluido",
      "Hosting incluido",
      "Diseño responsive",
      "Optimización SEO",
      "Email info@tumarca.com",
      "Hasta 5 páginas (Sobre mi, Servicios, Proyectos, Contacto)",
      "Entrega en 2-3 semanas",
    ],
  },
  {
    title: "Personalizado",
    price: undefined,
    salePrice: undefined,
    bestSeller: false,
    description: "Apps y sistemas complejos",
    features: [
      "Aplicaciones web complejas",
      "Sistemas de gestión",
      "Automatizaciones",
      "Integraciones API",
      "Tiempo según alcance",
    ],
  },
  {
    title: "E-commerce WordPress + WooCommerce",
    price: 760,
    priceArs: 920000,
    // salePrice: null,
    bestSeller: false,
    description:
      "Tienda online completa con control total, SEO avanzado y escalabilidad ilimitada.",
    features: [
      "Dominio .com.ar incluido",
      "Hosting incluido",
      "Diseño responsive y a medida",
      "Optimización SEO avanzada",
      "Email info@tumarca.com",
      "Catálogo de productos",
      "Carrito de compras",
      "Pasarela de pagos",
      "Panel de administración avanzado",
      "Entrega en 3-4 semanas",
      "Desarrollo en Wordpress (Open Source)",
    ],
  },

  {
    title: "Tienda Online con Tiendanube",
    price: 280,
    priceArs: 300000,
    // salePrice: null,
    bestSeller: true,
    description:
      "Tu tienda profesional en la plataforma líder de Latam. Solución rápida y completa.",
    features: [
      "Dominio .com.ar incluido",
      "Plataforma Tiendanube (SaaS)",
      "Diseño responsive",
      "Configuración de Medios de Pago y Envío básicos",
      "Carga inicial de Catálogo de Productos (Hasta 20 productos)",
      "Integración con Mercado Pago y Pasarelas",
      "Capacitación de uso del panel",
      "Entrega en 1-2 semanas",
      "Panel de administración básico y amigable",
    ],
  },
  {
    title: "Tienda Online con Empretienda",
    price: 280,
    priceArs: 300000,
    // salePrice: null,
    bestSeller: false,
    description:
      "La opción más económica y simple para lanzar tu tienda. Ideal para emprendedores iniciales.",
    features: [
      "Dominio .com.ar incluido",
      "Plataforma Empretienda (SaaS)",
      "Diseño responsive",
      "Configuración de Medios de Pago y Envío básicos",
      "Carga inicial de Catálogo de Productos (Hasta 20 productos)",
      "Capacitación de uso del panel",
      "Entrega en 1-2 semanas",
      "Panel de administración básico y amigable",
    ],
  },
];
