export const pricing = [
  {
    title: "Landing Page",
    description: "Perfecta para lanzamientos y campañas",
    bestSeller: false,
    price: 250,
    salePrice: 199,
    features: [
      "Dominio incluido",
      "Hosting incluido",
      "Diseño responsive",
      "Optimización SEO",
      "Email info@tumarca.com",
      "1 página",
      "Entrega en 1-2 semanas",
    ],
  },
  {
    title: "Web Corporativa",
    bestSeller: true,
    price: 450,
    salePrice: 399,
    description: "Para empresas y profesionales",
    features: [
      "Dominio incluido",
      "Hosting incluido",
      "Diseño responsive",
      "Optimización SEO",
      "Email info@tumarca.com",
      "Hasta 5 páginas (Sobre mi, Servicios, Proyectos, Contacto)",
      "Entrega en 2-3 semanas",
    ],
  },
  {
    title: "E-commerce",
    price: 750,
    salePrice: 699,
    bestSeller: false,
    description: "Tienda online completa",
    features: [
      "Dominio incluido",
      "Hosting incluido",
      "Diseño responsive",
      "Optimización SEO",
      "Email info@tumarca.com",
      "Catálogo de productos",
      "Carrito de compras",
      "Pasarela de pagos",
      "Panel de administración",
      "Entrega en 3-4 semanas",
      "Desarrollo en Wordpress",
    ],
  },
  {
    title: "Personalizado",
    price: undefined,
    salePrice: undefined,
    bestSeller: false,
    description: "Apps y sistemas complejos",
    features: [
      "Aplicaciones web complejas",
      "Sistemas de gestión",
      "Automatizaciones",
      "Integraciones API",
      "Tiempo según alcance",
    ],
  },
];
